FUNCTION(STM32_GET_FAMITY_X CHIP FAMITY_X)
    SET(re "^[sS][tT][mM]32(....).(.)")
    STRING(REGEX REPLACE ${re} "\\1" STM32_SERIES ${CHIP})
    STRING(REGEX REPLACE ${re} "\\2" STM32_SIZE_CODE ${CHIP})
    STRING(TOUPPER ${STM32_SERIES} STM32_SERIES)
    STRING(TOUPPER ${STM32_SIZE_CODE} STM32_SIZE_CODE)

    set(${FAMITY_X} STM32${STM32_SERIES}x${STM32_SIZE_CODE} PARENT_SCOPE)
ENDFUNCTION()
